# chart-repo: stable/sonatype-nexus
# chart-version: latest
# chart-pvc: sonatype-nexus-data ReadWriteOnce 30Gi

nexus:
  # imageName: quay.io/travelaudience/docker-nexus
  # imageTag: 3.13.0
  serviceType: SERVICE_TYPE
  resources:
    requests:
      cpu: 1000m
      memory: 2048Mi
    limits:
      cpu: 2000m
      memory: 4096Mi
  livenessProbe:
    initialDelaySeconds: 300
    periodSeconds: 30
    failureThreshold: 12
    path: /
  readinessProbe:
    initialDelaySeconds: 300
    periodSeconds: 30
    failureThreshold: 12
    path: /

nexusProxy:
  # imageName: quay.io/travelaudience/docker-nexus-proxy
  # imageTag: 2.3.0
  env:
    nexusHttpHost: INGRESS_DOMAIN
    nexusDockerHost: docker-INGRESS_DOMAIN

ingress:
  enabled: INGRESS_ENABLED
  tls:
    enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    ingress.kubernetes.io/proxy-body-size: 500m

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  storageSize: 30Gi
  #:EFS:storageClass: "efs"
  existingClaim: sonatype-nexus-data

resources:
  requests:
    cpu: 1000m
    memory: 5120Mi
